In [1]:
import numpy as np 
import pandas as pd

In [11]:
df=pd.read_csv(r'C:\Users\SANKET\Desktop\DSMP Capstone Project - Copy\House Price Prediction\data\gurgaon\analytics.csv')
df

,sector,price,price_per_sqft,built_up_area,bedRoom,bathroom,property_type,latitude,longitude
0,sector 36,0.82,7586.0,850.0,3.0,2.0,flat,28.4160,76.9914
1,sector 89,0.95,8597.0,1226.0,2.0,2.0,flat,28.4253,76.9439
2,sohna road,0.32,5470.0,1000.0,2.0,2.0,flat,NaN,NaN
3,sector 92,1.60,8020.0,1615.0,3.0,4.0,flat,28.4079,76.9153
4,sector 102,0.48,9023.0,582.0,2.0,2.0,flat,28.4750,76.9715
...,...,...,...,...,...,...,...,...,...
3549,sector 84,0.37,6346.0,532.0,2.0,2.0,flat,28.3979,76.9736
3550,sector 109,6.00,9634.0,6228.0,5.0,5.0,house,28.5073,77.0089
3551,sector 2,0.60,8163.0,665.0,1.0,1.0,flat,28.5095,77.0320
3552,sector 43,15.50,28233.0,5490.0,5.0,6.0,house,28.4629,77.0772
3553,sector 68,1.78,9128.0,1845.0,3.0,3.0,flat,28.3853,77.0484

In [3]:
df1=pd.read_csv(r'C:\Users\SANKET\Desktop\DSMP Capstone Project - Copy\House Price Prediction\data\mumbai\analytics.csv')
df1

,price,area,locality,property_type,bedroom_num,latitude,longitude
0,6600283,757,Kalyan,Apartment,2,19.244410,73.123253
1,6169841,652,Kalyan,Apartment,2,19.257294,73.148872
2,4599936,396,Dombivali,Apartment,1,19.209026,73.081276
3,51980000,1130,Ville Parle,Apartment,3,19.097841,72.851158
4,3915000,435,Nala Sopara,Apartment,1,19.420601,72.809319
...,...,...,...,...,...,...,...
71933,38931000,683,Dadar,Apartment,2,19.018014,72.832026
71934,54663000,959,Dadar,Apartment,3,19.018014,72.832026
71935,15135866,422,Andheri,Apartment,1,19.124240,72.842760
71936,25500000,713,Andheri,Apartment,2,19.124240,72.842760
71937,27384000,978,Andheri,Apartment,3,19.124240,72.842760

In [12]:
 df.rename(columns={
    "sector": "location",
    "bedRoom": "bedroom",
    "built_up_area": "area"
},inplace=True)

In [13]:
df

,location,price,price_per_sqft,area,bedroom,bathroom,property_type,latitude,longitude
0,sector 36,0.82,7586.0,850.0,3.0,2.0,flat,28.4160,76.9914
1,sector 89,0.95,8597.0,1226.0,2.0,2.0,flat,28.4253,76.9439
2,sohna road,0.32,5470.0,1000.0,2.0,2.0,flat,NaN,NaN
3,sector 92,1.60,8020.0,1615.0,3.0,4.0,flat,28.4079,76.9153
4,sector 102,0.48,9023.0,582.0,2.0,2.0,flat,28.4750,76.9715
...,...,...,...,...,...,...,...,...,...
3549,sector 84,0.37,6346.0,532.0,2.0,2.0,flat,28.3979,76.9736
3550,sector 109,6.00,9634.0,6228.0,5.0,5.0,house,28.5073,77.0089
3551,sector 2,0.60,8163.0,665.0,1.0,1.0,flat,28.5095,77.0320
3552,sector 43,15.50,28233.0,5490.0,5.0,6.0,house,28.4629,77.0772
3553,sector 68,1.78,9128.0,1845.0,3.0,3.0,flat,28.3853,77.0484

In [14]:
df1.rename(columns={
    "locality": "location",
    "bedroom_num": "bedroom"
},inplace=True)

In [15]:
df1

,price,area,location,property_type,bedroom,latitude,longitude
0,6600283,757,Kalyan,Apartment,2,19.244410,73.123253
1,6169841,652,Kalyan,Apartment,2,19.257294,73.148872
2,4599936,396,Dombivali,Apartment,1,19.209026,73.081276
3,51980000,1130,Ville Parle,Apartment,3,19.097841,72.851158
4,3915000,435,Nala Sopara,Apartment,1,19.420601,72.809319
...,...,...,...,...,...,...,...
71933,38931000,683,Dadar,Apartment,2,19.018014,72.832026
71934,54663000,959,Dadar,Apartment,3,19.018014,72.832026
71935,15135866,422,Andheri,Apartment,1,19.124240,72.842760
71936,25500000,713,Andheri,Apartment,2,19.124240,72.842760
71937,27384000,978,Andheri,Apartment,3,19.124240,72.842760

In [16]:
df

,location,price,price_per_sqft,area,bedroom,bathroom,property_type,latitude,longitude
0,sector 36,0.82,7586.0,850.0,3.0,2.0,flat,28.4160,76.9914
1,sector 89,0.95,8597.0,1226.0,2.0,2.0,flat,28.4253,76.9439
2,sohna road,0.32,5470.0,1000.0,2.0,2.0,flat,NaN,NaN
3,sector 92,1.60,8020.0,1615.0,3.0,4.0,flat,28.4079,76.9153
4,sector 102,0.48,9023.0,582.0,2.0,2.0,flat,28.4750,76.9715
...,...,...,...,...,...,...,...,...,...
3549,sector 84,0.37,6346.0,532.0,2.0,2.0,flat,28.3979,76.9736
3550,sector 109,6.00,9634.0,6228.0,5.0,5.0,house,28.5073,77.0089
3551,sector 2,0.60,8163.0,665.0,1.0,1.0,flat,28.5095,77.0320
3552,sector 43,15.50,28233.0,5490.0,5.0,6.0,house,28.4629,77.0772
3553,sector 68,1.78,9128.0,1845.0,3.0,3.0,flat,28.3853,77.0484

In [18]:
df1.to_csv('analyticsM.csv',index=False)